services:
  web:
    build:
      context: ${APP_ROOT:-/opt/1panel/apps/showukb}
      dockerfile: ${APP_ROOT:-/opt/1panel/apps/showukb}/Dockerfile
    container_name: showukb-web
    restart: unless-stopped
    environment:
      DB_PROVIDER: postgres
      DATABASE_URL: postgresql://showukb:ECNQh2maQadcPPad@1Panel-postgresql-QwRz:5432/showukb
      PORT: 3000
    ports:
      - "10001:3000"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
